name: Add new source
description: 
title: "[Add]: "
labels: ["add", "source"]
assignees:
  - octocat
body:
  - type: input
    id: url
    attributes:
      label: URL
      description: Please provide the URL where the issue occurred.
      placeholder: ex. https://example.com
